import { Product } from "../models/Product/Product";

export const testProducts: Product[] = [
  {
    id: 1,
    name: "Apple",
    calories: 52,
    proteins: 0.3,
    carbs: 14,
    fats: 0.2,
    fiber: 2.4,
    price: 0.5,
    createdBy: "Admin",
  },
  {
    id: 2,
    name: "Banana",
    calories: 96,
    proteins: 1.3,
    carbs: 27,
    fats: 0.3,
    fiber: 2.6,
    price: 0.3,
    createdBy: "Admin",
  },
  {
    id: 3,
    name: "Chicken Breast",
    calories: 165,
    proteins: 31,
    carbs: 0,
    fats: 3.6,
    fiber: 0,
    price: 3.0,
    createdBy: "Admin",
  },
  {
    id: 4,
    name: "Broccoli",
    calories: 55,
    proteins: 3.7,
    carbs: 11.2,
    fats: 0.6,
    fiber: 3.6,
    price: 1.2,
    createdBy: "Admin",
  },
  {
    id: 5,
    name: "Almonds",
    calories: 579,
    proteins: 21,
    carbs: 22,
    fats: 50,
    fiber: 12.5,
    price: 15.0,
    createdBy: "Admin",
  },
  {
    id: 6,
    name: "Salmon",
    calories: 208,
    proteins: 20,
    carbs: 0,
    fats: 13,
    fiber: 0,
    price: 10.0,
    createdBy: "Admin",
  },
  {
    id: 7,
    name: "Eggs",
    calories: 155,
    proteins: 13,
    carbs: 1.1,
    fats: 11,
    fiber: 0,
    price: 0.2,
    createdBy: "Admin",
  },
  {
    id: 8,
    name: "Oatmeal",
    calories: 68,
    proteins: 2.4,
    carbs: 12,
    fats: 1.4,
    fiber: 1.7,
    price: 0.8,
    createdBy: "Admin",
  },
  {
    id: 9,
    name: "Sweet Potato",
    calories: 86,
    proteins: 1.6,
    carbs: 20,
    fats: 0.1,
    fiber: 3,
    price: 1.0,
    createdBy: "Admin",
  },
  {
    id: 10,
    name: "Quinoa",
    calories: 120,
    proteins: 4.1,
    carbs: 21.3,
    fats: 1.9,
    fiber: 2.8,
    price: 4.5,
    createdBy: "Admin",
  },
  {
    id: 11,
    name: "Greek Yogurt",
    calories: 59,
    proteins: 10,
    carbs: 3.6,
    fats: 0.4,
    fiber: 0,
    price: 1.5,
    createdBy: "Admin",
  },
  {
    id: 12,
    name: "Avocado",
    calories: 160,
    proteins: 2,
    carbs: 9,
    fats: 15,
    fiber: 7,
    price: 1.2,
    createdBy: "Admin",
  },
  {
    id: 13,
    name: "Spinach",
    calories: 23,
    proteins: 2.9,
    carbs: 3.6,
    fats: 0.4,
    fiber: 2.2,
    price: 0.9,
    createdBy: "Admin",
  },
  {
    id: 14,
    name: "Blueberries",
    calories: 57,
    proteins: 0.7,
    carbs: 14,
    fats: 0.3,
    fiber: 2.4,
    price: 2.5,
    createdBy: "Admin",
  },
  {
    id: 15,
    name: "Brown Rice",
    calories: 111,
    proteins: 2.6,
    carbs: 23,
    fats: 0.9,
    fiber: 1.8,
    price: 1.0,
    createdBy: "Admin",
  },
  {
    id: 16,
    name: "Tofu",
    calories: 76,
    proteins: 8,
    carbs: 2,
    fats: 4.8,
    fiber: 0.3,
    price: 2.0,
    createdBy: "Admin",
  },
  {
    id: 17,
    name: "Oranges",
    calories: 47,
    proteins: 0.9,
    carbs: 12,
    fats: 0.1,
    fiber: 2.4,
    price: 0.6,
    createdBy: "Admin",
  },
  {
    id: 18,
    name: "Strawberries",
    calories: 32,
    proteins: 0.7,
    carbs: 7.7,
    fats: 0.3,
    fiber: 2,
    price: 2.3,
    createdBy: "Admin",
  },
  {
    id: 19,
    name: "Walnuts",
    calories: 654,
    proteins: 15,
    carbs: 14,
    fats: 65,
    fiber: 6.7,
    price: 12.0,
    createdBy: "Admin",
  },
  {
    id: 20,
    name: "Turkey Breast",
    calories: 135,
    proteins: 30,
    carbs: 0,
    fats: 1.2,
    fiber: 0,
    price: 4.0,
    createdBy: "Admin",
  },
  {
    id: 21,
    name: "Peanut Butter",
    calories: 588,
    proteins: 25,
    carbs: 20,
    fats: 50,
    fiber: 6,
    price: 2.5,
    createdBy: "Admin",
  },
  {
    id: 22,
    name: "Cottage Cheese",
    calories: 98,
    proteins: 11,
    carbs: 3.4,
    fats: 4.3,
    fiber: 0,
    price: 1.8,
    createdBy: "Admin",
  },
  {
    id: 23,
    name: "Mango",
    calories: 60,
    proteins: 0.8,
    carbs: 15,
    fats: 0.4,
    fiber: 1.6,
    price: 1.0,
    createdBy: "Admin",
  },
  {
    id: 24,
    name: "Chia Seeds",
    calories: 486,
    proteins: 16.5,
    carbs: 42.1,
    fats: 30.7,
    fiber: 34.4,
    price: 9.0,
    createdBy: "Admin",
  },
  {
    id: 25,
    name: "Bell Pepper",
    calories: 31,
    proteins: 1,
    carbs: 6,
    fats: 0.3,
    fiber: 2.1,
    price: 1.0,
    createdBy: "Admin",
  },
];
